In [12]:
import numpy as np
x = np.arange(9.).reshape(3,  3)
print(x)
# 过滤掉每行最后一个小于6的元素
# print(x[~(x[:, -2] < 8), :])
# 截取小数点后两位
# print(np.around(x, 2))

# 每行第一个数为0时，过滤掉最后一个小于0.3的元素
print(x[(x[:, 0] == 0) & (x[:, -1] < 0.3), :])
print(x[(x[:, 0] == 1) & (x[:, -1] < 0.3), :])
print(x[(x[:, 0] == 2) & (x[:, -1] < 0.3), :])

# 打印 赵于婷



[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
[]
[]
[]
